

purpose    : trace FiRe
description: configures how to log to stdout and roling file

---
# *** YAML2LOG4R ***
log4r_config:
  # define all pre config ...
  pre_config:
    custom_levels:
      - DEBUG
      - INFO
      - PRT
      - WARN
      - ERROR
      - FATAL
    global:
      level: FATAL
    root  :
      level: FATAL
    parameters:
      - name   : x
        value  : aaa
      - name   : y
        value  : bbb

  # define all loggers ...
  loggers:
    - name      : log
      level     : INFO
      additive  : 'false'
      trace     : 'false'      
      outputters:
        - stderr
        - stdout
        - logfile 
        - errlogfile 

  # define all outputters (incl. formatters)      
  outputters:
    - type     : StderrOutputter
      name     : stderr 
      level    : DEBUG
      only_at  :
        - ERROR
        - FATAL
      formatter:
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter
    - type     : StdoutOutputter
      name     : stdout 
      level    : DEBUG
      formatter:
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter

    - type        : DateFileOutputter
      name        : logfile
      level       : DEBUG
      date_pattern: '%Y%m%d'
      trunc       : 'false'
      dirname     : "#{HOME}/logs"
      formatter   :
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : '%d %l: %m'
        type        : PatternFormatter

    - type        : DateFileOutputter
      name        : errlogfile
      level       : DEBUG
      date_pattern: '%Y%m%d%H'
      trunc       : 'false'
      dirname     : "#{HOME}/logs"
      formatter   :
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : '%d %l: %m'
        type        : PatternFormatter